account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy


app_name = 'account'


urlpatterns = [
    path('signin/', UserCreationView.as_view(), name='signin'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('item:list')), name='logout'),
    path('<str:username>/update/', UserUpdateView.as_view(), name='update'),
    path('passwordchange/', UserPasswordChangeView.as_view(), name='passwordchange'),

    path('<str:username>/profile/create/', ProfileCreateView.as_view(), name='profile-create'),
    path('<str:username>/profile/update/', ProfileUpdateView.as_view(), name='profile-update'),

    path('<str:username>/cprofile/create/', CompanyProfileCreateView.as_view(), name='companyprofile-create'),
    path('<slug:username>/cprofile/update/', CompanyProfileUpdateView.as_view(), name='companyprofile-update'),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
]

api/urls.py
from django.urls import path
from .views import *


app_name = 'api'

urlpatterns = [
    path('home', ItemListAPIView.as_view(), name='item-list'),
    path('item/create/', ItemCreateAPIView.as_view(), name='item-create'),
    path('item/<slug:slug>/<int:pk>/', ItemRetrieveAPIView.as_view(), name='item-ddu'),
    path("item/comment/create", CommentCreateAPIView.as_view(), name="comment-create"),
    path("address/create/", AddressCreateView.as_view(), name="address-create"),
    path("addresses/", AddressListAPIView.as_view(), name="address-list"),
    path("addresses/<int:pk>/", AddressUpdateAPIView.as_view(), name="address-update"),
    path("basket/<int:pk>/", BasketView.as_view(), name="basket"),
    path("myitems/", MyItemListView.as_view(), name="my-items"),
    path("order/<str:username>/<int:pk>/", OrderitemRetrieveDestroyAPIView.as_view(), name="orderitem-delete"),

    path("account/create/", UserCreationAPIView.as_view(), name="account-creation"),
    path("account/<str:username>/", UserRetrieveUpdateAPIView.as_view(), name="account-retrieveupdate"),
    path("account/passwordchange/", UserChangePasswordAPIView.as_view(), name="account-changepassword"),
    path("profile/<str:username>/", ProfileRetrieveUpdateAPIView.as_view(), name="profile-update"),
    path("companyprofile/create/", CompanyProfileCreateAPIView.as_view(), name="companyprofile-create"),
    path("companyprofile/update/<str:username>/", CompanyProfileRetrieveUpdateAPIView.as_view(), name="companyprofile-update"),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'


urlpatterns = [
    path('', ItemListView.as_view(), name='list'),
    path('item/create/', ItemCreateView.as_view(), name='create'),
    path('item/<slug:slug>/<int:pk>', ItemDetailView.as_view(), name='detail'),
    path('item/<slug:slug>/<int:pk>/update/', ItemUpdateView.as_view(), name='update'),
    path("address/", AddressView.as_view(), name="address"),
    path("address/<int:pk>/", AddressUpdateView.as_view(), name="address-update"),
    path("address/create/", AddressCreateView.as_view(), name="address-create"),
    path("<str:username>/basket/", BasketView.as_view(), name="basket"),
    path("myitem/", MyItemListView.as_view(), name="myitem"),
    path("item/category/<str:name>/", ItemListCategoryView.as_view(), name="itemscategory"),
    path("watchlist/", WatchListView.as_view(), name="watchlist"),
    path("addwatchlist/", AddWatchlist.as_view(), name="addwatchlist"),
    path("removewatchlist/", RemoveWatchlist.as_view(), name="removewatchlist"),
]

masoud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from swagger.views import get_swagger_view
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


schema_view = get_swagger_view(title='Pastebin API')

schema_view2 = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('cv-masoud-admin/', admin.site.urls),
    path('', include('item.urls')),
    path('api/', include('api.urls')),
    path('', include('account.urls')),

    path('swagger/', schema_view),
    path('redoc/', schema_view2.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from ast import Return
import re
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
from .validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _


GENDER = (("MALE", "مرد"),
          ("FEMALE", "زن"))

REGEX_HOME_PHONE_NUMBER = RegexValidator(regex='^(\+98|0)?\d{10}$', message="شماره وارد شده اشتباه است\n01712345678")


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(_('شماره تلفن'),
                                max_length=13,
                                unique=True,
                                help_text=_('09123456789'),
                                validators=[username_validator],
                                error_messages={
                                    'unique': _("A user with that mobile number already exists."),},)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', verbose_name="کاربر")
    image = models.ImageField(upload_to='profile/%Y/%m/%d/', blank=True, null=True, verbose_name="عکس پروفایل")
    bio = models.TextField(blank=True, null=True, verbose_name="درمورد من")
    gender = models.CharField(max_length=25, choices=GENDER, blank=True, null=True, verbose_name="جنسیت")

    class Meta:
        ordering = ['user', ]
        verbose_name_plural = "پروفایل مشتری ها"
        verbose_name = "پروفایل مشتری"

    def __str__(self):
        return str(self.user)


class CompanyProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cprofile', verbose_name="شرکت")
    name = models.CharField(max_length=250, default=None)
    image = models.ImageField(upload_to='Cprofile/%Y/%m/%d/', blank=True, null=True, verbose_name="عکس پروفال")
    home_phone_number = models.CharField(max_length=13, validators=[REGEX_HOME_PHONE_NUMBER], default=None, unique=True,
                                         verbose_name="شماره تلفن شرکت")
    bio = models.TextField(blank=True, null=True, verbose_name="درمورد شرکت")
    address_company = models.TextField(verbose_name="آدرس")
    confirm = models.BooleanField(default=False, verbose_name="تاییدیه شرکت")

    def get_name(self, user):
        try:
            cp = CompanyProfile.objects.get(user=user)
        except CompanyProfile.DoesNotExist:
            return "Masoud Company"
        return cp.name

    class Meta:
        ordering = ['user', ]
        verbose_name_plural = "پروفایل فروشنده ها"
        verbose_name = "پروفایل فروشنده"

    def __str__(self):
        return str(self.user)

account/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.views import View
from django.views.generic import CreateView, UpdateView
from django.views.generic.edit import FormMixin
from django.urls import reverse
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth import logout, get_user_model

from .forms import *
from .models import *
from .mixins import *


User = get_user_model()


class DashboardView(LoginRequiredMixin, View):
    template_name = "dashboard.html"

    def get(self, request, *args, **kwargs):
        return redirect('account:update', username=request.user.username, )


class UserCreationView(UserCreateLoginMixin ,CreateView):
    model = User
    template_name = 'create.html'
    form_class = UserCreateForm

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, "ثبت نام شما با موفقیت انجام شد")
        return reverse('account:login')


class UserLoginView(UserCreateLoginMixin, LoginView):
    template_name = 'login.html'
    form_class = UserLoginForm

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, "شما وارد سایت شدید.")
        return reverse('item:list')
    

class UserUpdateView(OwnerOrSuperuserMixin, UpdateView):
    template_name = 'update.html'
    form_class = UserUpdateForm

    def get_object(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        return user

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, "اکانت با موفقیت ویرایش شد.")
        return reverse('account:dashboard')
    

class ProfileCreateView(OwnerOrSuperuserMixin, CreateView):
    template_name = 'profile-create.html'
    model = Profile
    form_class = ProfileCreateForm

    def get_object(self, *args, **kwargs):
        return get_object_or_404(User, username=self.kwargs['username'])

    def get_form_kwargs(self):
        kwargs = super(ProfileCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST,request.FILES, request=request)
        if form.is_valid():
            if request.user.is_superuser:
                profile = Profile.objects.create(**form.cleaned_data)
            else:
                user = request.user
                profile = Profile.objects.create(user=user, **form.cleaned_data)
            profile.save()
            messages.success(request, "پروفایل با موفقیت ثبت شد")
            return HttpResponseRedirect(reverse("account:dashboard"))


class ProfileUpdateView(ProfileUpdateOwnerOrSuperuserMixin, UpdateView):
    model = Profile
    template_name = 'Profile-update.html'
    form_class = ProfileUpdateForm

    def get_object(self, *args, **kwargs):
        return get_object_or_404(Profile, user__username=self.kwargs['username'])

    def get_form_kwargs(self):
        kwargs = super(ProfileUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, "پروفایل با موفقیت ویرایش شد")
        return reverse('account:dashboard')


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'password_change.html'
    form_class = UserPasswordChangeForm
    login_url = "account:login"

    def get_success_url(self):
        logout(self.request)
        messages.add_message(self.request, messages.SUCCESS, "گذرواژه با موفقیت تغییر کرد")
        return reverse('account:login')


class CompanyProfileCreateView(OwnerOrSuperuserMixin, CreateView):
    template_name = 'cprofile-create.html'
    form_class = CompanyProfileForm

    def get_object(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        return user

    def get_form_kwargs(self):
        kwargs = super(CompanyProfileCreateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def post(self, request, *args, **kwargs):
        form = CompanyProfileForm(request.POST, request.FILES, request=request)
        if form.is_valid():
            home_phone_number = form.cleaned_data['home_phone_number']
            # 02134567899
            home_phone_number = "0" + home_phone_number[-10:]
            try:
                CompanyProfile.objects.get(home_phone_number=home_phone_number)
            except CompanyProfile.DoesNotExist:
                if request.user.is_superuser:
                    user = form.cleaned_data['user']
                    confirm = form.cleaned_data['confirm']
                else:
                    user = self.request.user
                    confirm = False
                new_profile = CompanyProfile.objects.create(user=user,
                                                            image=form.cleaned_data['image'],
                                                            bio=form.cleaned_data['bio'],
                                                            name=form.cleaned_data['name'],
                                                            address_company=form.cleaned_data['address_company'],
                                                            home_phone_number=home_phone_number,
                                                            confirm=confirm)
                new_profile.save()
                try:
                    profile = Profile.objects.get(user=user)
                except Profile.DoesNotExist:
                    messages.success(request, "ثبت نام با موفقیت انجام شد. پس از تایید پروفایل می توایند محصول اضافه کنید.")
                    return HttpResponseRedirect(reverse("account:dashboard"))
                profile.delete()
                messages.success(request, "ثبت نام با موفقیت انجام شد. پس از تایید پروفایل می توایند محصول اضافه کنید.")
                return HttpResponseRedirect(reverse("account:dashboard"))
            else:
                messages.error(request, "این شماره از قبل موجود است")
        form = CompanyProfileForm(request=request)
        return render(request, self.template_name, {"form": form})


class CompanyProfileUpdateView(ProfileUpdateOwnerOrSuperuserMixin, UpdateView):
    model = CompanyProfile
    template_name = "cprofile-update.html"
    form_class = CompanyProfileForm

    def get_object(self, *args, **kwargs):
        return get_object_or_404(CompanyProfile, user__username=self.kwargs['username'])

    def get_form_kwargs(self):
        kwargs = super(CompanyProfileUpdateView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    
    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, "پروفایل با موفقیت ویرایش شد")
        return reverse('account:dashboard')

account/templates/Profile-update.html
{% extends 'dashboard.html' %}

{% block dtitle %}ویرایش پروفایل{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">ویرایش پروفایل</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% if request.user.is_superuser %}
            <div class="form-group">
                {{ form.user }}
            </div>
            {% endif %}
            <div class="form-group">
                {{ form.gender }}
            </div>
            <div class="form-group">
                {{ form.image }}
            </div>
            <div class="form-group">
                {{ form.bio }}
            </div>
            <input type='submit' value="ویرایش" class="primary-btn order-submit" style="padding: 12px 300px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
{% endblock %}

account/templates/cprofile-create.html
{% extends 'dashboard.html' %}

{% block dtitle %}ساخت پروفایل شرکتی{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">ساخت حساب شرکتی</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% if request.user.is_superuser %}
            <div class="form-group">
                {{ form.user }}
            </div>
            <div class="input-checkbox">
                {{ form.confirm }}
                <label for="shiping-address">
                    <span></span>
                    تاییدیه شرکت
                </label>
            </div>
            {% endif %}
            <div class="form-group">
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.home_phone_number }}
            </div>
            {{ form.image }}<br>
            <div class="form-group">
                {{ form.bio }}
            </div>
            <div class="form-group">
                {{ form.address_company }}
            </div>
            <input type='submit' value="ثبت" class="primary-btn order-submit" style="padding: 12px 300px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
{% endblock %}

account/templates/cprofile-update.html
{% extends 'dashboard.html' %}

{% block dtitle %}ویرایش پروفایل شرکتی{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">ویرایش حساب شرکتی</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% if request.user.is_superuser %}
            <div class="form-group">
                {{ form.user }}
            </div>
            {% endif %}
            <div class="form-group">
                {{ form.gender }}
            </div>
            <div class="form-group">
                {{ form.image }}
            </div>
            <div class="form-group">
                {{ form.bio }}
            </div>
            <input type='submit' value="ویرایش" class="primary-btn order-submit" style="padding: 12px 300px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
{% endblock %}

account/templates/create.html
{% extends 'base.html' %}
{% block title %}ثبت نام{% endblock %}

{% block content %}
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
        <!-- Order Details -->
                <div class="col-md-5 order-details" style="margin-left:29%;margin-top:180px;">
                    <div class="section-title text-center">
                        <h3 class="title">ثبت نام</h3>
                    </div>
                    <form method='post'>
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            {{ form.first_name }}
                        </div>
                        <div class="form-group">
                            {{ form.last_name }}
                        </div>
                        <div class="form-group">
                            {{ form.password1 }}
                        </div>
                        <div class="form-group">
                            {{ form.password2 }}
                        </div>
                        <input type='submit' value="ثبت" class="primary-btn order-submit" style="padding:12px 46%">    
                    </form>
                </div>
                <!-- /Order Details -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->
{% endblock %}

account/templates/dashboard.html
{% extends 'base.html' %}
{% block title %}{% block dtitle %}{% endblock dtitle %}{% endblock %}

{% block navigation %}
{% url 'account:update' request.user.username as update_user_url %}
{% url 'account:passwordchange' as passwordchange_url %}
{% url 'account:profile-update' request.user.username as profile_update_url %}
{% url 'account:companyprofile-create' request.user.username as companyprofile_create_url %}
{% url 'account:companyprofile-update' request.user.username as companyprofile_update_url %}
{% url 'item:create' as item_create_url %}
{% url 'item:myitem' as myitem_url %}
{% url 'account:profile-create' request.user.username as profile_create_url %}
{% url 'item:basket' request.user.username as basket_url %}
{% url 'item:address' as address_url %}
{% url 'item:address-create' as address_create_url %}
<!-- NAVIGATION -->
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                {% if request.user.first_name %}
                    <li {% if request.path == update_user_url %}class="active"{% endif %}><a href="{{update_user_url}}">{{ request.user.first_name }}</a></li>
                {% else %}
                    <li {% if request.path == update_user_url %}class="active"{% endif %}><a href="{{update_user_url}}">{{ request.user }}</a></li>
                {% endif %}
                <li {% if request.path == passwordchange_url %}class="active"{% endif %}><a href="{{passwordchange_url}}">تغییر رمز عبور</a></li>
                {% if request.user.profile %}
                    <li {% if request.path == profile_update_url %}class="active"{% endif %}><a href="{{ profile_update_url }}">ویرایش پروفایل</a></li>
                    <li {% if request.path == companyprofile_create_url %}class="active"{% endif %}><a href="{{ companyprofile_create_url }}">ساخت حساب شرکتی</a></li>
                
                {% elif request.user.cprofile and request.user.cprofile.confirm == True %}
                    <li {% if request.path == companyprofile_update_url %}class="active"{% endif %}><a href="{{ companyprofile_update_url }}">ویرایش پروفایل</a></li>
                    <li {% if request.path == item_create_url %}class="active"{% endif %}><a href="{{ item_create_url }}">افزودن محصول</a></li>
                    <li {% if request.path == myitem_url %}class="active"{% endif %}><a href="{{ myitem_url }}">محصولات من</a></li>
                {% elif request.user.cprofile and request.user.cprofile.confirm == False %}
                    <li {% if request.path == companyprofile_update_url %}class="active"{% endif %}><a href="{{ companyprofile_update_url }}">ویرایش پروفایل</a></li>
                {% else %}
                    <li {% if request.path == profile_create_url %}class="active"{% endif %}><a href="{{ profile_create_url }}">تکمیل پروفایل</a></li>
                    <li {% if request.path == companyprofile_create_url %}class="active"{% endif %}><a href="{{ companyprofile_create_url }}">ساخت حساب شرکتی</a></li>
                {% endif %}
                {% if request.user.is_superuser %}
                    <li {% if request.path == profile_create_url %}class="active"{% endif %}><a href="{{ profile_create_url }}">ساخت پروفایل</a></li>
                    <li {% if request.path == companyprofile_create_url %}class="active"{% endif %}><a href="{{ companyprofile_create_url }}">ساخت حساب شرکتی</a></li>
                {% endif %}
                {% if request.user.customer.items.all %}
                    <li {% if request.path == basket_url %}class="active"{% endif %}><a href="{{ basket_url }}">سبد خرید</a></li>
                {% endif %}
                {% if request.user.address_user.all %}
                    <li {% if request.path == address_url %}class="active"{% endif %}><a href="{{ address_url }}">آدرس ها</a></li>
                {% endif %}
                <li {% if request.path == address_create_url %}class="active"{% endif %}><a href="{{ address_create_url }}">افزودن آدرس</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<!-- /NAVIGATION -->
{% endblock navigation %}

{% block content %}<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            {% block dcontent %}{% endblock dcontent %}
            <!-- Order Details -->
            <div class="col-md-5 order-details">
                {% if request.user.profile.image %}
                <div class="section-title text-center">
                    <img src="{{ request.user.profile.image.url }}" height="425.5px" width="425.5px">
                </div>
                {% elif request.user.cprofile.image %}
                <div class="section-title text-center">
                    <img src="{{ request.user.cprofile.image.url }}" height="425.5px" width="425.5px">
                </div>
                {% endif %}
                
                <div class="order-summary">
                    <div class="order-col">
                        <div><strong>{{ request.user.username }}</strong></div>
                        <div><strong>شماره موبایل</strong></div>
                    </div>
                    <div class="order-col">
                        {% if request.user.email %}
                        <div><strong>{{ request.user.email }}</strong></div>
                        {% else %}
                        <div><strong>-</strong></div>
                        {% endif %}
                        <div><strong>ایمیل</strong></div>
                    </div>
                    <div class="order-products">
                        <div class="order-col">
                            {% if request.user.first_name %}
                            <div><strong>{{ request.user.first_name }}</strong></div>
                            {% else %}
                            <div><strong>-</strong></div>
                            {% endif %}
                            <div><strong>نام</strong></div>
                        </div>
                        <div class="order-col">
                            {% if request.user.last_name %}
                            <div><strong>{{ request.user.last_name }}</strong></div>
                            {% else %}
                            <div><strong>-</strong></div>
                            {% endif %}
                            <div><strong>نام خانوادگی</strong></div>
                        </div>
                    </div>
            </div>
            <!-- /Order Details -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->
</div>
{% endblock content %}

account/templates/login.html
{% extends 'base.html' %}
{% block title %}ورود{% endblock %}

{% block content %}
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
        <!-- Order Details -->
                <div class="col-md-5 order-details" style="margin-left:29%;margin-top:21.5%;">
                    <div class="section-title text-center">
                        <h3 class="title">ورود به سایت</h3>
                    </div>
                    <form method='post'>
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            {{ form.password }}
                        </div>
                        <input type='submit' value="ورود" class="primary-btn order-submit" style="padding:12px 46%">    
                    </form>
                </div>
                <!-- /Order Details -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /SECTION -->
{% endblock %}

account/templates/password_change.html
{% extends 'dashboard.html' %}

{% block dtitle %}تغییر رمز عبور{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">تغییر رمز عبور</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.old_password }}
            </div>
            <div class="form-group">
                {{ form.new_password1 }}
            </div>
            <div class="form-group">
                {{ form.new_password2 }}
            </div>
            <input type='submit' value="ویرایش" class="primary-btn order-submit" style="padding: 12px 300px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
<div class="col-5">
</div>
{% endblock %}

account/templates/profile-create.html
{% extends 'dashboard.html' %}

{% block dtitle %}تکمیل پروفایل{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">ویرایش حساب</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {% if request.user.is_superuser %}
            <div class="form-group">
                {{ form.user }}
            </div>
            {% endif %}
            <div class="form-group">
                {{ form.gender }}
            </div>
            <div class="form-group">
                {{ form.image }}
            </div>
            <div class="form-group">
                {{ form.bio }}
            </div>
            <input type='submit' value="ویرایش" class="primary-btn order-submit" style="padding: 12px 300px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
{% endblock %}

account/templates/update.html
{% extends 'dashboard.html' %}

{% block dtitle %}ویرایش حساب{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">ویرایش حساب</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.first_name }}
            </div>
            <div class="form-group">
                {{ form.last_name }}
            </div>
            <div class="form-group">
                {{ form.username }}
            </div>
            <div class="form-group">
                {{ form.email }}
            </div>
            <input type='submit' value="ویرایش" class="primary-btn order-submit" style="padding: 12px 300px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
{% endblock %}