account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy


app_name = 'account'


urlpatterns = [
    path('signin/', UserCreationView.as_view(), name='signin'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('item:list')), name='logout'),
    path('<str:username>/update/', UserUpdateView.as_view(), name='update'),
    path('passwordchange/', UserPasswordChangeView.as_view(), name='passwordchange'),

    path('<str:username>/profile/create/', ProfileCreateView.as_view(), name='profile-create'),
    path('<str:username>/profile/update/', ProfileUpdateView.as_view(), name='profile-update'),

    path('<str:username>/cprofile/create/', CompanyProfileCreateView.as_view(), name='companyprofile-create'),
    path('<slug:username>/cprofile/update/', CompanyProfileUpdateView.as_view(), name='companyprofile-update'),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
]

api/urls.py
from django.urls import path
from .views import *


app_name = 'api'

urlpatterns = [
    path('home', ItemListAPIView.as_view(), name='item-list'),
    path('item/create/', ItemCreateAPIView.as_view(), name='item-create'),
    path('item/<slug:slug>/<int:pk>/', ItemRetrieveAPIView.as_view(), name='item-ddu'),
    path("item/comment/create", CommentCreateAPIView.as_view(), name="comment-create"),
    path("address/create/", AddressCreateView.as_view(), name="address-create"),
    path("addresses/", AddressListAPIView.as_view(), name="address-list"),
    path("addresses/<int:pk>/", AddressUpdateAPIView.as_view(), name="address-update"),
    path("basket/<int:pk>/", BasketView.as_view(), name="basket"),
    path("myitems/", MyItemListView.as_view(), name="my-items"),
    path("order/<str:username>/<int:pk>/", OrderitemRetrieveDestroyAPIView.as_view(), name="orderitem-delete"),

    path("account/create/", UserCreationAPIView.as_view(), name="account-creation"),
    path("account/<str:username>/", UserRetrieveUpdateAPIView.as_view(), name="account-retrieveupdate"),
    path("account/passwordchange/", UserChangePasswordAPIView.as_view(), name="account-changepassword"),
    path("profile/<str:username>/", ProfileRetrieveUpdateAPIView.as_view(), name="profile-update"),
    path("companyprofile/create/", CompanyProfileCreateAPIView.as_view(), name="companyprofile-create"),
    path("companyprofile/update/<str:username>/", CompanyProfileRetrieveUpdateAPIView.as_view(), name="companyprofile-update"),
]

item/urls.py
from django.urls import path
from .views import *

app_name = 'item'


urlpatterns = [
    path('', ItemListView.as_view(), name='list'),
    path('item/create/', ItemCreateView.as_view(), name='create'),
    path('item/<slug:slug>/<int:pk>', ItemDetailView.as_view(), name='detail'),
    path('item/<slug:slug>/<int:pk>/update/', ItemUpdateView.as_view(), name='update'),
    path("address/", AddressView.as_view(), name="address"),
    path("address/<int:pk>/", AddressUpdateView.as_view(), name="address-update"),
    path("address/create/", AddressCreateView.as_view(), name="address-create"),
    path("<str:username>/basket/", BasketView.as_view(), name="basket"),
    path("myitem/", MyItemListView.as_view(), name="myitem"),
    path("item/category/<str:name>/", ItemListCategoryView.as_view(), name="itemscategory"),
    path("watchlist/", WatchListView.as_view(), name="watchlist"),
    path("addwatchlist/", AddWatchlist.as_view(), name="addwatchlist"),
    path("removewatchlist/", RemoveWatchlist.as_view(), name="removewatchlist"),
]

masoud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from swagger.views import get_swagger_view
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


schema_view = get_swagger_view(title='Pastebin API')

schema_view2 = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('cv-masoud-admin/', admin.site.urls),
    path('', include('item.urls')),
    path('api/', include('api.urls')),
    path('', include('account.urls')),

    path('swagger/', schema_view),
    path('redoc/', schema_view2.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.views.generic import *
from .forms import *
from django.urls import reverse
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from .mixins import *
from account.mixins import ProfileUpdateOwnerOrSuperuserMixin
from django.db.models import Q, F
from django.core.paginator import Paginator


class ItemListView(ListView):
    template_name = 'home.html'
    paginate_by = 6
    queryset = Item.objects.filter(status="p").order_by('-inventory', "date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        p = Paginator(self.queryset, self.paginate_by)
        context["items"] = p.page(context['page_obj'].number)
        context["categories"] = Category.objects.all()
        context['search_form'] = ItemSearchForm()
        context['addbasketlist_form'] = AddbasketListForm()
        if self.request.user.is_authenticated:
            context['num_watchlist'] = WatchList.num_watchlist(self, self.request.user)
        else:
            context['num_watchlist'] = 0
        context['average_dict'] = Comment.get_averages_dict(self, self.queryset)
        if self.request.user.is_authenticated:
            context['are_there_watchlist'] = WatchList.are_there_watchlist(self, self.queryset, self.request.user)
            context['num_basket'] = Order.get_number_basket(self, self.request.user)
            context['items_basket'] = Order.get_items_basket(self, self.request.user)
            context['final_price'] = Order.get_final_price_order(self, self.request.user)
        return context

    def post(self, request, *args, **kwargs):
        self.object_list = self.queryset
        context = {}
        if "search" in request.POST:
            search_form = ItemSearchForm(request.POST)
            if search_form.is_valid():
                qs = Item.objects.search(query=search_form.cleaned_data['lookup']).filter(status="p")
                ctxt = {"qs": qs}
                return render(request, "itemsearch.html", context=ctxt)
            else:
                context["search_form"] = search_form
                    
        for item in self.object_list.filter(~Q(inventory=0)):    
            if str(item) in request.POST:
                if request.user == item.company:
                    messages.error(request, "این محصول شماست نمیتوانید به سبد خود ارسال کنید")
                    return redirect("item:list")

                try:
                    update_orderitem = OrderItem.objects.get(item=item, customer=request.user)
                except OrderItem.DoesNotExist:
                    new_orderitem = OrderItem.objects.create(item=item,
                                                                count=1,
                                                                customer=request.user)
                    new_orderitem.save()
                else:
                    update_orderitem.count += 1
                    update_orderitem.save()

                try:
                    update_order = Order.objects.get(user=request.user)
                except Order.DoesNotExist:
                    new_order = Order(
                        user=request.user,
                    )
                    new_order.save()
                    new_order.items.add(OrderItem.objects.get(item=item, customer=request.user))
                else:
                    update_order.items.add(OrderItem.objects.get(item=item, customer=request.user))
                messages.success(request, "به سبد اضافه شد")
                return HttpResponseRedirect(reverse('item:list'))
        return render(request, self.template_name, self.get_context_data(**context))


class ItemDetailView(PublishedItemMixin, View):
    template_name = 'itemdetail.html'

    def get_object(self):
        item = get_object_or_404(Item, slug=self.kwargs['slug'], pk=self.kwargs['pk'])
        return item

    def get_context_data(self, **kwargs):
        kwargs['item'] = self.get_object()
        kwargs['company_name'] = CompanyProfile.get_name(self, self.get_object().company)
        same_items = []
        for tag in self.get_object().tags.all():
            same_items += Item.objects.filter(tags=tag).filter(~Q(name=self.get_object().name))
        kwargs["same_items"] = same_items
        if 'orderitem_form' not in kwargs:
            kwargs['orderitem_form'] = OrderItemForm()
        if 'comment_form' not in kwargs:
            kwargs['comment_form'] = CommentForm()
        kwargs['dict_point_users'] = Comment.dict_point_users(self, self.get_object())
        if self.request.user.is_authenticated:
            kwargs['is_there_watchlist'] = WatchList.is_there_watchlist(self, self.request.user, self.get_object())
        kwargs['comments'] = Comment.objects.filter(item=self.get_object()).filter(~Q(user=None))
        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        context = {}
        if 'comment' in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                text = comment_form.cleaned_data['text']
                if 'rating' in request.POST:
                    point = int(request.POST['rating'])
                else:
                    point = None
                item = self.get_object()
                user = request.user
                new_comment = Comment(item=item, user=user, text=text, point=point)
                new_comment.save()
                messages.success(request, "کامت شما ثبت شد")
                return redirect('item:detail', pk=item.pk, slug=item.slug)
            else:
                context['response_form'] = CommentForm

        elif 'orderitem' in request.POST:
            orderitem_form = OrderItemForm(request.POST)
            item = self.get_object()
            if orderitem_form.is_valid():
                count = orderitem_form.cleaned_data['count']
                if count == 0:
                    messages.error(request, "هیچ تعداد محصولی انتخاب نکرده اید")
                    return redirect('item:detail', pk=item.pk, slug=item.slug)
                elif count > item.inventory:
                    messages.info(request, "بیش از حد ظرفیت موجود")
                    return redirect('item:detail', pk=item.pk, slug=item.slug)
                elif request.user == item.company:
                    messages.error(request, "این محصول شماست نمیتوانید به سبد خود ارسال کنید")
                    return redirect("item:detail", pk=item.pk, slug=item.slug)

                try:
                    update_orderitem = OrderItem.objects.get(item=item, customer=request.user, color=orderitem_form.cleaned_data['color'])
                except OrderItem.DoesNotExist:
                    new_orderitem = OrderItem.objects.create(item=item,
                                                             count=count,
                                                             color=request.POST['color'],
                                                             customer=request.user)
                    new_orderitem.save()
                else:
                    update_orderitem.count += count
                    update_orderitem.save()

                try:
                    update_order = Order.objects.get(user=request.user)
                except Order.DoesNotExist:
                    new_order = Order(
                        user=request.user,
                    )
                    new_order.save()
                    new_order.items.add(OrderItem.objects.get(item=item, color=request.POST['color'], customer=request.user))
                else:
                    update_order.items.add(OrderItem.objects.get(item=item, color=request.POST['color'], customer=request.user))
                messages.success(request, "به سبد اضافه شد")
                return HttpResponseRedirect(reverse('item:detail', args=[item.slug, item.id, ]))
            else:
                context['response_form'] = CommentForm

        elif "deleteitem" in request.POST:
            item = self.get_object()
            item.delete()
            messages.success(request, "محصول شما حذف شد")
            return HttpResponseRedirect(reverse("item:list"))

        elif "empty" in request.POST:
            item = self.get_object()
            item.inventory = 0
            item.save()
            messages.success(request, "محصول ناموجود شد")
            return HttpResponseRedirect(reverse("item:detail", args=[item.slug, item.id, ]))
        
        elif str(self.get_object()) + "add" in request.POST:
            watchlist = WatchList.objects.create(user=request.user, item=self.get_object())
            watchlist.save()
            messages.success(request, "به علاقه مندی ها اضافه شد")
            return HttpResponseRedirect(reverse("item:detail", args=[self.get_object().slug, self.get_object().id, ]))

        elif str(self.get_object()) + "del" in request.POST:
            watchlist = WatchList.objects.get(user=request.user, item=self.get_object())
            watchlist.delete()
            messages.success(request, "از علاقه مندی ها حذف شد")
            return HttpResponseRedirect(reverse("item:detail", args=[self.get_object().slug, self.get_object().id, ]))

        return render(request, self.template_name, self.get_context_data(**context))


class ItemUpdateView(ItemUpdateMixin, UpdateView):
    form_class = ItemForm
    template_name = 'itemupdate.html'
    context_object_name = "item"

    def get_object(self):
        item = get_object_or_404(Item, slug=self.kwargs['slug'], pk=self.kwargs['pk'])
        return item

    def get_form_kwargs(self):

item/templates/addresslist.html
{% extends 'dashboard.html' %}

{% block dtitle %}آدرس های من{% endblock dtitle %}

{% block dcontent %}
<div class="col-md-7">
    <!-- Billing Details -->
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">آدرس ها</h3>
        </div>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {% for address in addresses %}
            <div class="form-group">
                <div class="input-checkbox">
                    <input class="input" style="width:15px;" type="radio" id="{{address.pk}}" name="fav-language" value="{{address.home_address}}" {% if address.this_address == True %}checked{% endif %}>
                    <label class="input" for="{{address.pk}}">
                        <span></span>
                        {{ address.home_address }}
                    </label>
                    {% comment %} <br><a href="{% url 'item:address-update' address.pk %}">ویرایش</a> {% endcomment %}
                </div>
                <a href="{% url 'item:address-update' address.pk %}">ویرایش</a>
            </div>
            {% endfor %}<br>
            <input type='submit' value="ثبت" name="choose" class="primary-btn order-submit" style="padding: 12px 313.4px">    
        </form>
    </div>
    <!-- /Billing Details -->
</div>
{% endblock %}

item/templates/base.html
{% load static %}
{% load item_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!-- Google font -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

        <!-- Bootstrap -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

        <!-- Slick -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

        <!-- nouislider -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

        <!-- Font Awesome Icon -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!-- Custom stlylesheet -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>
    </head>
    <body>
      <header>
        <!-- TOP HEADER -->
        <div id="top-header">
          <div class="container">
            <ul class="header-links pull-left">
              <li><a href="{% url 'item:list' %}"><i class="fa fa-home"></i>MasoudKazak</a></li>
              <li><a href="#"><i class="fa fa-phone"></i> +98-939-920-2913</a></li>
              <li><a href="#"><i class="fa fa-envelope-o"></i> kzmasut@gmail.com</a></li>
              <li><a href="#"><i class="fa fa-map-marker"></i>گلستان - تهران</a></li>
            </ul>
            <ul class="header-links pull-right">
              {% if request.user.is_authenticated %}
              <li><a href="{% url 'account:dashboard' %}"><i class="fa fa-user-o"></i>
                  {% if request.user.first_name and request.user.last_name %}  
                  {{ request.user.first_name }} {{ request.user.last_name  }}
                  {% else %}
                    {{ request.user }}
                  {% endif %}
                </a></li>
                <li><a href="{% url 'account:logout' %}">خروج</a></li>
              {% else %}
                <li><a href="{% url 'account:login' %}"><i class="fa fa-user-o"></i>
                  ورود
                </a></li>
                <li><a href="{% url 'account:signin' %}">ثبت نام</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
        <!-- /TOP HEADER -->
  
        <!-- MAIN HEADER -->
        <div id="header">
          <!-- container -->
          <div class="container">
            <!-- row -->
            <div class="row">
              <!-- LOGO -->
              <div class="col-md-3">
                <div class="header-logo">
                  <a href="#" class="logo">
                    <img src="./img/logo.png" alt="">
                  </a>
                </div>
              </div>
              <!-- /LOGO -->
  
              <!-- SEARCH BAR -->
              <div class="col-md-6">
                <div class="header-search">
                    {% block category %}{% block search %}{% endblock search %}{% endblock category %}
                </div>
              </div>
              <!-- /SEARCH BAR -->
  
              <!-- ACCOUNT -->
              <div class="col-md-3 clearfix">
                <div class="header-ctn">
                  {% block watchlist %}{% endblock watchlist %}
                  {% block num_basket %}{% endblock num_basket %}
                  <!-- Menu Toogle -->
                  <div class="menu-toggle">
                    <a href="#">
                      <i class="fa fa-bars"></i>
                      <span>Menu</span>
                    </a>
                  </div>
                  <!-- /Menu Toogle -->
                </div>
              </div>
              <!-- /ACCOUNT -->
            </div>
            <!-- row -->
          </div>
          <!-- container -->
        </div>
        <!-- /MAIN HEADER -->
      </header>
      <!-- /HEADER -->
      {% block navigation %}{% endblock navigation %}

      {% if messages %}
          {% for message in messages %}
          <div {% if message.tags == "info" %} class="alert alert-info alert-dismissible fade show" 
                {% elif message.tags == "error" %} class="alert alert-danger alert-dismissible fade show"
                {% elif message.tags == "success" %} class="alert alert-success alert-dismissible fade show"
                {% endif %} role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
          {% endfor %}
      {% endif %}
      {% block content %}{% endblock content %}<br><br>

      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/slick.min.js' %}"></script>
      <script src="{% static 'js/nouislider.min.js' %}"></script>
      <script src="{% static 'js/jquery.zoom.min.js' %}"></script>
      <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

item/templates/home.html
{% extends 'base.html' %}
{% load item_tags %}
{% block title %}Home{% endblock title %}

{% block category %}
<form method="post">
  <select class="input-select" onchange="location = this.value;">
    <option selected value="{% url 'item:list' %}">همه</option>
    {% for category in categories %}
      {% if category.items.all|length != 0 %}
        <option value="{% url 'item:itemscategory' category.name %}">{{ category.name }}</option>
      {% endif %}
    {% endfor %}
  </select>
  {% block search %}
  {% csrf_token %}
  {{ search_form }}
  <button class="search-btn" name="search">جستجو</button>
{% endblock %}
</form>
{% endblock %}

{% block num_basket %}
{% if request.user.is_authenticated %}
<!-- Cart -->
<div class="dropdown">

  <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true" href="{% url 'item:basket' request.user.username %}">
    <i class="fa fa-shopping-cart"></i>
    <span>سبد خرید</span>
    <div class="qty">{{ num_basket }}</div>
  </a>
  <div class="cart-dropdown">
    <div class="cart-list">
      {% for orderitem in items_basket %}
      <div class="product-widget">
        <div class="product-img">
          <img src="{{ orderitem.item.images.all.0.image.url }}" alt="" height="60px" weight="60px">
        </div>
        <div class="product-body">
          <h3 class="product-name"><a href="{% url 'item:detail' orderitem.item.slug orderitem.item.pk %}">{{ orderitem.item.name }}</a></h3>
          <h4 class="product-price"><span class="qty">{{ orderitem.count }}x</span>{{ orderitem.item.final_price }}</h4>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="cart-summary">
      <small>{{ items_basket|length }} محصول انتخاب کرده اید</small>
      <h5>کل پرداختی: {{ final_price }} تومان</h5>
    </div>
    {% if request.user.is_authenticated %}
    <div class="cart-btns">
      <a href="{% url 'item:basket' request.user.username %}">سبد خرید</a>
      <a href="#">تکمیل خرید  <i class="fa fa-arrow-circle-right"></i></a>
    </div>
    {% endif %}
  </div>
</div>
<!-- /Cart -->
{% endif %}
{% endblock %}

{% block watchlist %}
<!-- Wishlist -->
{% if request.user.is_authenticated %}
<div>
  <a href="{% url 'item:watchlist' %}">
    <i class="fa fa-heart-o"></i>
    <span>Your Wishlist</span>
    <div class="qty">{{ num_watchlist }}</div>
  </a>
</div>
{% endif %}
<!-- /Wishlist -->
{% endblock watchlist %}

{% block content %}
<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <!-- ASIDE -->
      {% comment %} <div id="aside" class="col-md-3">
        <!-- aside Widget -->
          <div class="aside">
            <h3 class="aside-title">Price</h3>
            <div class="price-filter">
              <div id="price-slider"></div>
              <div class="input-number price-min">
                <input class="filter-price" id="price-min" type="number" data-catid="min_price">
                <span class="qty-up">+</span>
                <span class="qty-down">-</span>
              </div>
              <span>-</span>
              <div class="input-number price-max">
                <input class="filter-price" id="price-max" type="number" name="max_price">
                <span class="qty-up">+</span>
                <span class="qty-down">-</span>
              </div>
              <input type="submit" value="filter">
            </div>
          </div>
        <!-- /aside Widget -->
      </div> {% endcomment %}
      <!-- /ASIDE -->

      <!-- STORE -->
      {% comment %} <div id="store" class="col-md-9">
        <!-- store top filter -->
        <div class="store-filter clearfix">
          <div class="store-sort">
            <label>
              Sort By:
              <select class="input-select">
                <option value="0">Popular</option>
                <option value="1">Position</option>
              </select>
            </label>

            <label>
              Show:
              <select class="input-select">
                <option value="0">20</option>
                <option value="1">50</option>
              </select>
            </label>
          </div>
        </div> {% endcomment %}
        <!-- /store top filter -->

        <!-- store products -->
        <div class="row">
          <!-- product -->
          {% for item in items %}
          <div class="col-md-3 col-xs-6">
            <div class="product">
              <div class="product-img">
                <a href="{% url 'item:detail' item.slug item.pk %}"><img src="{{ item.images.all.0.image.url }}" alt="" width="262.5px" height="262.5px"></a>
                <div class="product-label">
                  {% if item.inventory != 0 %}
                    {% if item.discount %}
                      <span class="sale">-{{ item.int_discount }}</span>
                    {% endif %}
                  {% endif %}
                  {% if forloop.counter0 == 0 or forloop.counter0 == 1 or forloop.counter0 == 2 %}
                  <span class="new">NEW</span>
                  {% endif %}
                </div>
              </div>
              <div class="product-body">
                <p class="product-category">{{ item.category }}</p>
                <h3 class="product-name"><a href="{% url 'item:detail' item.slug item.pk %}">{{ item.name }}</a></h3>
                {% if item.inventory == 0 %}
                  <h4 class="product-price">تمام</h4>
                  <h4 class="product-price">شد</h4>
                {% else %}
                  {% if item.discount %}
                    <h4 class="product-price">{{ item.final_price }} <del class="product-old-price">{{ item.price_without_discount }}</del></h4>
                    <h4 class="product-price">تومان</h4>
                   {% else %}
                    <h4 class="product-price">{{ item.final_price }}</h4>
                    <h4 class="product-price">تومان</h4>
                  {% endif %}
                {% endif %}
                <div class="product-rating">
                  {% for average in average_dict|get_value_dict:item.name|number_to_range_point|get_index_list:0 %}
                    <i class="fa fa-star"></i>
                  {% endfor %}
                  {% for average in average_dict|get_value_dict:item.name|number_to_range_point|get_index_list:1 %}
                    <i class="fa fa-star-o"></i>
                  {% endfor %}
                </div>
                <div class="product-btns">
                  {% if request.user.is_authenticated %}
                  {% if are_there_watchlist|get_value_dict:item.name %}
                  <a class="removewatch" id="remove{{item.id}}" href="#" data-catid="{{ item.id }}"><i class="fa fa-heart"></i></a>
                  {% else %}
                  <a class="addwatch" id="add{{item.id}}" href="#" data-catid="{{ item.id }}"><i class="fa fa-heart-o"></i></a>
                  {% endif %}
                  {% endif %}
                </div>
              </div>
              {% if item.inventory != 0 and request.user.is_authenticated %}
              <div class="add-to-cart">
                <form method="post">
                  {% csrf_token %}
                <button class="add-to-cart-btn" name="{{ item }}"><i class="fa fa-shopping-cart"></i> افزودن به سبد</button>
              </form>
              </div>
              {% endif %}
            </div>
          </div>
          {% endfor %}
          <!-- /product -->
          <!-- store bottom filter -->
						<div class="store-filter clearfix">
							<ul class="store-pagination">
                {% if page_obj.has_previous %}
                  <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                {% for n in page_obj.paginator.page_range %}
                  {% if page_obj.number == n %}
                    <li class="active">{{ n }}</li>
                  {% else %}
                    <li><a href="?page={{ n }}">{{ n }}</a></li>
                  {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
								  <li><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
						</div>
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script type="text/javascript">
    $('.removewatch').click(function(){
    var catid;
    catid = $(this).attr("data-catid");
    $.ajax(
    {
        type:"GET",
        url: "/removewatchlist",
        data:{
                 item_id: catid
        },
        success: function( data ) 
        {
          location.reload()
        }
     })
    });
    $('.addwatch').click(function(){
    var catid;
    catid = $(this).attr("data-catid");
    $.ajax(
    {
      type:"GET",
      url: "/addwatchlist",
      data:{
                item_id: catid
            },
      success: function( data ) 
        {
          location.reload()
        }
      })
    });
  </script>
{% endblock content %}